// Dependency-free MOCK DOM tests. These verify UI state code, not real browser layout/media.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=JSON.parse(fs.readFileSync(path.join(root,'fixtures/source_pack.json'))),artifacts=JSON.parse(fs.readFileSync(path.join(root,'fixtures/good.json')));
class Element{constructor(tag){this.tagName=tag;this.children=[];this.value='';this.hidden=false;this.disabled=false;this.style={};this.events={};this._text='';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this._text='';this.children=nodes;}addEventListener(name,fn){this.events[name]=fn;}}
const ids=['message','history','facts','sourcejson','sourcehash','runlabel','origin','artifactjson','export','artifacts','reviews','reviewcount','results','good','bad','live','evaluate','correct','save'];const nodes=Object.fromEntries(ids.map(id=>[id,Object.assign(new Element('div'),{id})]));
const walk=n=>[n,...n.children.flatMap(walk)];const all=()=>Object.values(nodes).flatMap(walk);const doc={getElementById:id=>nodes[id]||all().find(n=>n.id===id),createElement:tag=>new Element(tag),querySelectorAll:selector=>all().filter(n=>n.tagName===selector)};
let reqs=[];let config={csrf:'test-token',default_mode:'replay',live_enabled:false,ffmpeg_available:true,source,runs:[]};let responseRun={id:'123456abcdef',version:1,mode:'replay',source,source_hash:'a'.repeat(64),artifacts,reviews:{},render:null,evaluations:null};
const context=vm.createContext({document:doc,Option:function(t,v){const n=new Element('option');n.textContent=t;n.value=v;return n;},confirm:()=>false,console,fetch:async(url,opts)=>{if(opts)reqs.push(JSON.parse(opts.body));return {ok:true,json:async()=>url==='/api/config'?config:structuredClone(responseRun)};}});
const checks=[];function ok(name){checks.push({name,passed:true});}
(async()=>{vm.runInContext(fs.readFileSync(path.join(root,'web/app.js'),'utf8'),context);await new Promise(setImmediate);
assert(nodes.message.textContent.includes('Replay ready'));assert(nodes.live.hidden);assert.equal(nodes.facts.children.length,9);ok('default replay, nine source facts and live button hidden');
await nodes.good.onclick();assert.equal(nodes.artifacts.children.length,4);assert(nodes.evaluate.disabled);assert(doc.getElementById('approve-video').disabled);assert(nodes.origin.textContent.includes('not evidence of a live'));ok('four artifact cards, honest replay label and gated evaluation/video approval');
assert.equal(reqs[0].mode,'replay');assert.equal(reqs[0].scenario,'good');ok('good replay sends correct bounded request');
context.testRun=structuredClone(responseRun);context.testRun.source.source_facts[0].text='<img src=x onerror=alert(1)>';vm.runInContext('run=testRun;draw()',context);assert(nodes.facts.textContent.includes('<img src=x'));assert(!all().some(n=>n.tagName==='img'));ok('source strings rendered via textContent, no created HTML image node');
context.testRun=structuredClone(responseRun);for(const k of ['newsletter','linkedin','x','video'])context.testRun.reviews[k]={decision:'changes_requested',version:1};vm.runInContext('run=testRun;draw()',context);assert(!nodes.evaluate.disabled);ok('four human decisions unlock formal checks even when changes requested');
context.testRun.version=2;context.testRun.reviews={};vm.runInContext('run=testRun;draw()',context);assert(nodes.evaluate.disabled);assert(nodes.reviewcount.textContent.includes('0 / 4'));ok('new version with reset reviews relocks evaluation');
nodes.artifactjson.value='{broken';nodes.save.onclick();assert(nodes.message.textContent.includes('JSON could not be read'));ok('invalid edit JSON produces clear UI error');
responseRun=structuredClone(responseRun);responseRun.render={filename:'sample.mp4',width:1080,height:1920,duration:30,renderer:'fixture'};context.testRun=responseRun;vm.runInContext('run=testRun;draw()',context);assert(doc.getElementById('approve-video').disabled);const video=all().find(n=>n.tagName==='video');video.events.ended();assert(!doc.getElementById('approve-video').disabled);ok('mocked video-ended event enables decision; actual media playback not tested here');
responseRun.reviews.newsletter={decision:'approved',version:1};await vm.runInContext("api({action:'review',id:run.id,version:1,kind:'newsletter',decision:'approved'})",context);assert(doc.getElementById('approve-video').disabled===false);ok('watching unchanged video remains valid after a text review action');
responseRun.version=2;responseRun.render=null;responseRun.reviews={};await vm.runInContext("api({action:'revise',id:run.id,version:1,artifacts:run.artifacts})",context);assert(doc.getElementById('approve-video').disabled);ok('new version resets playback evidence');
const result={type:'mocked DOM state tests, NOT browser rendering or media playback',checks};fs.writeFileSync(path.join(root,'evidence/ui-state-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})();
