'use strict';
let config,run,busy=false,videoPlayed=false;
const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function playbackKey(r){return r&&r.render?[r.id,r.version,r.render.filename,r.render.at,r.render.video_hash,r.render.source_hash].join('|'):null;}
function message(text,error=false){$('message').textContent=text;$('message').style.background=error?'#973d35':'#16353b';}
async function api(data){if(busy)return;busy=true;lock();message('Working… Keep this window open');try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Classroom-Token':config.csrf},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error);const priorKey=playbackKey(run),priorPlayed=videoPlayed;run=v;videoPlayed=priorPlayed&&priorKey!==null&&priorKey===playbackKey(run);draw();await refreshHistory();message(`Version ${run.version} saved · ${run.mode==='replay'?'Synthetic fixture replay; no model called':'Live managed Agents API draft'} · No publication`);}catch(e){message(e.message,true);}finally{busy=false;lock();}}
function lock(){$('history').disabled=busy;document.querySelectorAll('button').forEach(b=>b.disabled=busy);if(!run){['save','correct','evaluate'].forEach(id=>$(id).disabled=true);return;}$('evaluate').disabled=busy||Object.keys(run.reviews).length!==4;$('correct').disabled=busy||run.mode!=='replay';const b=$('approve-video');if(b)b.disabled=busy||!run.render||!videoPlayed;}
function sourceDraw(s){$('facts').replaceChildren(...s.source_facts.map(f=>{let d=el('div',undefined,'fact');d.append(el('strong',f.id),el('p',f.text));return d;}));$('sourcejson').value=JSON.stringify(s,null,2);$('sourcehash').textContent=run?'source '+run.source_hash.slice(0,12):'F01–F09 / fixed teaching facts';}
function draw(){sourceDraw(run.source);$('runlabel').textContent=`${run.mode.toUpperCase()} / v${run.version} / ${run.id}`;$('origin').textContent=run.mode==='replay'?'Human-authored synthetic fixture. These are practice outputs, not evidence of a live model run.':'Generated through the managed OpenAI Agents API. Human review is still required.';$('artifactjson').value=JSON.stringify(run.artifacts,null,2);$('export').hidden=false;$('export').href='/export/'+run.id;
let cards=[];for(const k of ['newsletter','linkedin','x','video']){const a=run.artifacts[k],d=el('article',undefined,'artifact');d.append(el('span',k==='video'?'Silent social video':k,'tag'));if(a.title)d.append(el('h3',a.title));if(a.body)d.append(el('div',a.body,'bodytext'));if(a.citations)d.append(el('div','Sources: '+a.citations.join(', '),'cites'));if(k==='video'){a.scenes.forEach((s,i)=>{const sc=el('div',undefined,'scene');sc.append(el('span',`SCENE ${i+1} · ${s.duration_seconds}s · ${s.citations.join(', ')}`),el('div',s.text,'bodytext'));d.append(sc);});const btns=el('div',undefined,'buttons');const render=el('button','Render MP4');render.onclick=()=>api({action:'render',id:run.id,version:run.version});const sample=el('button','Use included MP4','secondary');sample.onclick=()=>api({action:'sample_video',id:run.id,version:run.version});btns.append(render,sample);d.append(btns);if(run.render){let video=el('video');video.controls=true;video.preload='metadata';video.src='/media/'+run.render.filename;video.addEventListener('ended',()=>{videoPlayed=true;lock();message('Video played to the end. Now record your editorial decision for this version');});d.append(video,el('p',`${run.render.width} × ${run.render.height} · ${run.render.duration}s · Silent, no voiceover · ${run.render.renderer}`,'small'));}else d.append(el('p','Script only. Render a new MP4 or load the included matching fixture MP4 before approval.','warn'));}cards.push(d);}$('artifacts').replaceChildren(...cards);
let reviews=[];for(const k of ['newsletter','linkedin','x','video']){const r=run.reviews[k],d=el('div',undefined,'review');d.append(el('h3',k),el('div',r?`${r.decision==='approved'?'Approved':'Changes requested'} · v${r.version}`:'Awaiting your decision','decision'));const label=el('label','Review note (no personal data)');label.htmlFor='note-'+k;const note=el('textarea');note.id='note-'+k;note.value=r?.note||'';note.maxLength=1000;const btns=el('div',undefined,'buttons');for(const [decision,title] of [['approved','Approve draft'],['changes_requested','Request changes']]){const b=el('button',title,decision==='approved'?'':'secondary');b.id=(decision==='approved'?'approve-':'reject-')+k;b.onclick=()=>api({action:'review',id:run.id,version:run.version,kind:k,decision,note:note.value});btns.append(b);}d.append(label,note,btns);if(k==='video')d.append(el('p','Play the current MP4 to the end to enable approval.','small'));reviews.push(d);}$('reviews').replaceChildren(...reviews);$('reviewcount').textContent=`${Object.keys(run.reviews).length} / 4 REVIEWED`;
const e=run.evaluations;if(!e)$('results').replaceChildren(el('p','First record a decision for each draft, then run the checks.'));else{let items=[el('div',`${e.checks.filter(c=>c.passed).length} / ${e.checks.length} deterministic checks passed`,'checks-summary'),el('p',e.machine_checks_passed?'Machine rules passed. Complete the human rubric; this does not prove factual accuracy or authorize publication.':'Revision needed. Inspect failed checks and the human rubric before changing the draft.','warn')];e.checks.forEach(c=>{let d=el('div',undefined,'check '+(c.passed?'':'fail'));const text=el('div');text.append(el('strong',c.id),el('span',c.detail));d.append(el('span',c.passed?'PASS':'FAIL','resultmark'),text);items.push(d);});$('results').replaceChildren(...items);}lock();}
async function refreshHistory(){let r=await fetch('/api/config');config=await r.json();$('history').replaceChildren(new Option('Choose a run…',''),...config.runs.map(r=>new Option(`${r.mode} · ${r.scenario} · v${r.version} · ${r.id}`,r.id)));if(run)$('history').value=run.id;}
$('good').onclick=()=>api({action:'create',mode:'replay',scenario:'good'});$('bad').onclick=()=>api({action:'create',mode:'replay',scenario:'bad'});$('live').onclick=()=>{if(confirm('This sends the synthetic source pack to OpenAI and can incur API charges. Your server must already have an authorized key and project spend controls. Start one live run?'))api({action:'create',mode:'live',acknowledge_paid:true});};$('evaluate').onclick=()=>api({action:'evaluate',id:run.id,version:run.version});$('correct').onclick=()=>api({action:'rerun_fixed',id:run.id,version:run.version});$('save').onclick=()=>{try{api({action:'revise',id:run.id,version:run.version,artifacts:JSON.parse($('artifactjson').value),source:JSON.parse($('sourcejson').value)});}catch(e){message('JSON could not be read: '+e.message,true);}};$('history').onchange=async()=>{if(!$('history').value||busy)return;const selected=$('history').value;busy=true;lock();try{let r=await fetch('/api/run/'+selected);let v=await r.json();if(!r.ok)throw Error(v.error);run=v;videoPlayed=false;draw();message('Saved run loaded. Decisions remain tied to their recorded version');}catch(e){message(e.message,true);}finally{busy=false;lock();}};
(async()=>{try{await refreshHistory();sourceDraw(config.source);$('live').hidden=!config.live_enabled;message(config.ffmpeg_available?'Replay ready · No key or model calls required':'Replay ready · FFmpeg not found; use the included matching MP4 for the full review exercise');lock();}catch(e){message('Could not load the app. Start python server.py and open its local address',true);}})();
